version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: formokaizen_postgres
    environment:
      POSTGRES_DB: formokaizen
      POSTGRES_USER: formokaizen_user
      POSTGRES_PASSWORD: formokaizen_pass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: formokaizen_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  django:
    build: .
    container_name: formokaizen_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://formokaizen_user:formokaizen_pass123@postgres:5432/formokaizen
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

  celery:
    build: .
    container_name: formokaizen_celery
    command: celery -A formokaizen_backend worker -l info
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://formokaizen_user:formokaizen_pass123@postgres:5432/formokaizen
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

volumes:
  postgres_data:
  media_volume: