# Generated by Django 4.2.7 on 2025-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, verbose_name='Comentario interno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'tarjeta_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial',
                'db_table': 'tarjeta_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tarjetas/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de Tarjeta',
                'verbose_name_plural': 'Imágenes de Tarjetas',
                'db_table': 'tarjeta_images',
            },
        ),
        migrations.CreateModel(
            name='TarjetaRoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción del problema')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('pending_approval', 'Pendiente de Aprobación'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('resolved', 'Resuelta'), ('closed', 'Cerrada'), ('rejected', 'Rechazada')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20)),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sector específico')),
                ('motivo', models.TextField(verbose_name='Motivo/Causa raíz')),
                ('destino_final', models.TextField(verbose_name='Acción correctiva propuesta')),
                ('estimated_resolution_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de resolución')),
                ('actual_resolution_date', models.DateField(blank=True, null=True, verbose_name='Fecha real de resolución')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarjeta Roja',
                'verbose_name_plural': 'Tarjetas Rojas',
                'db_table': 'tarjetas_rojas',
                'ordering': ['-created_at'],
            },
        ),
    ]
