# Generated by Django 4.2.7 on 2025-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetaroja',
            name='actual_resolution_date',
        ),
        migrations.RemoveField(
            model_name='tarjetaroja',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tarjetaroja',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tarjetaroja',
            name='estimated_resolution_date',
        ),
        migrations.RemoveField(
            model_name='tarjetaroja',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='tarjetaroja',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tarjetaroja',
            name='work_area',
        ),
        migrations.AddField(
            model_name='tarjetaroja',
            name='descripcion',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='tarjetaroja',
            name='fecha',
            field=models.DateField(default='2024-01-01', verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='tarjetaroja',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final (Opcional)'),
        ),
        migrations.AddField(
            model_name='tarjetaroja',
            name='numero',
            field=models.CharField(default='TR-000', max_length=50, unique=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='tarjetaroja',
            name='quien_lo_hizo',
            field=models.CharField(default='Sin especificar', max_length=200, verbose_name='Quién lo hizo'),
        ),
        migrations.AddField(
            model_name='tarjetaroja',
            name='razon_motivo',
            field=models.TextField(default='Sin especificar', verbose_name='Razón/Motivo'),
        ),
        migrations.AlterField(
            model_name='tarjetaroja',
            name='destino_final',
            field=models.TextField(default='Sin especificar', verbose_name='Destino final'),
        ),
        migrations.AlterField(
            model_name='tarjetaroja',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='tarjetaroja',
            name='sector',
            field=models.CharField(default='Sin especificar', max_length=100, verbose_name='Sector'),
        ),
    ]
