# Generated by Django 4.2.7 on 2025-08-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
        ('tarjetas', '0003_remove_tarjetaroja_actual_resolution_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetaroja',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas', to='categories.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='tarjetaroja',
            name='work_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas', to='categories.workarea', verbose_name='Área de trabajo'),
        ),
    ]
