# Generated by Django 4.2.7 on 2025-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del equipo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('coordinator', 'Coordinador'), ('observer', 'Observador')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Membresía de Equipo',
                'verbose_name_plural': 'Membresías de Equipos',
                'db_table': 'team_memberships',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('target_end_date', models.DateField(verbose_name='Fecha objetivo de finalización')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha real de finalización')),
                ('status', models.CharField(choices=[('planning', 'Planificación'), ('active', 'Activo'), ('on_hold', 'En pausa'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='planning', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto de Equipo',
                'verbose_name_plural': 'Proyectos de Equipos',
                'db_table': 'team_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
