# Generated by Django 4.2.7 on 2025-08-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token de Dispositivo',
                'verbose_name_plural': 'Tokens de Dispositivos',
                'db_table': 'device_tokens',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('tarjeta_created', 'Nueva Tarjeta Roja'), ('tarjeta_assigned', 'Tarjeta Asignada'), ('tarjeta_approved', 'Tarjeta Aprobada'), ('tarjeta_rejected', 'Tarjeta Rechazada'), ('tarjeta_completed', 'Tarjeta Completada'), ('tarjeta_overdue', 'Tarjeta Vencida'), ('comment_added', 'Nuevo Comentario'), ('team_added', 'Agregado a Equipo'), ('team_removed', 'Removido de Equipo'), ('project_assigned', 'Proyecto Asignado'), ('system_update', 'Actualización del Sistema')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_tarjeta_created', models.BooleanField(default=True)),
                ('email_tarjeta_assigned', models.BooleanField(default=True)),
                ('email_tarjeta_approved', models.BooleanField(default=True)),
                ('email_tarjeta_overdue', models.BooleanField(default=True)),
                ('email_comment_added', models.BooleanField(default=False)),
                ('email_team_changes', models.BooleanField(default=True)),
                ('push_tarjeta_created', models.BooleanField(default=True)),
                ('push_tarjeta_assigned', models.BooleanField(default=True)),
                ('push_tarjeta_approved', models.BooleanField(default=True)),
                ('push_tarjeta_overdue', models.BooleanField(default=True)),
                ('push_comment_added', models.BooleanField(default=True)),
                ('push_team_changes', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='08:00')),
                ('weekend_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
                'db_table': 'notification_preferences',
            },
        ),
    ]
